Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_units(conversion, value):
    """Convert units based on user choice."""
    if conversion == "m_to_ft":
        return value * 3.28084
    elif conversion == "ft_to_m":
        return value * 0.3048
    elif conversion == "kg_to_lbs":
        return value * 2.20462
    elif conversion == "lbs_to_kg":
        return value * 0.453592
    elif conversion == "l_to_gal":
        return value * 0.264172
    elif conversion == "gal_to_l":
        return value * 3.78541
    else:
        return None  # Invalid choice

print("Unit Converter")
print("1. Meters to Feet\n2. Feet to Meters\n3. Kilograms to Pounds")
print("4. Pounds to Kilograms\n5. Liters to Gallons\n6. Gallons to Liters")

try:
    choice = int(input("Choose a conversion (1-6): "))
    value = float(input("Enter value to convert: "))

    conversions = {
        1: "m_to_ft",
        2: "ft_to_m",
        3: "kg_to_lbs",
        4: "lbs_to_kg",
        5: "l_to_gal",
        6: "gal_to_l"
    }

    if choice in conversions:
        result = convert_units(conversions[choice], value)
        print(f"Converted value: {result:.2f}")
    else:
        print("Invalid choice.")

except ValueError:
    print("Invalid input. Please enter a number.")


Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose a conversion (1-6): 4
Enter value to convert: 55
Converted value: 24.95


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def sum_list(numbers):

    return sum(numbers)

def average_list(numbers):

    return sum(numbers) / len(numbers) if numbers else 0

def max_list(numbers):

    return max(numbers) if numbers else None

def min_list(numbers):

    return min(numbers) if numbers else None

print("Mathematical Operations on a List")
print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

try:
    choice = input("Choose an operation (1-4): ")
    numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

    if not numbers:
        print("Error: The list cannot be empty.")
    elif choice == "1":
        print("Sum:", sum_list(numbers))
    elif choice == "2":
        print("Average:", average_list(numbers))
    elif choice == "3":
        print("Maximum:", max_list(numbers))
    elif choice == "4":
        print("Minimum:", min_list(numbers))
    else:
        print("Invalid choice. Please select a number between 1 and 4.")
except ValueError:
    print("Invalid input. Please enter numeric values.")


Mathematical Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 2
Enter numbers separated by spaces: 1 2 3c
Invalid input. Please enter numeric values.


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """Returns a new list containing every other element from the input list."""
    return lst[::2]

print("Welcome to array handler")
try:
    numbers = list(map(float, input("Enter the numbers here by adding space to each: ").split()))
    if not numbers:
        print("There are no numbers, please add numbers.")
    else:
        result = extract_every_other(numbers)
        print("Extracted list:", result)
except ValueError:
    print("Invalid input, please enter numeric values separated by spaces.")


Welcome to array handler
Enter the numbers here by adding space to each1 2 3 4 5 5
number recieved here: [1.0, 2.0, 3.0, 4.0, 5.0, 5.0]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [2]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [3]:
def reverse_list(lst):
    return lst[::-1]


print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [4]:
def remove_first_last(lst):
    return lst[1:-1]


print(remove_first_last([1, 2, 3, 4, 5]))


[2, 3, 4]


**5. Get the First n Elements:**
Write a Python function that extracts the first n elements from a list.

• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [6]:
def get_first_n(lst, n):
    return lst[:n]


print(get_first_n([1, 2, 3, 4, 5], 3))



def get_last_n(lst, n):
    return lst[-n:]


print(get_last_n([1, 2, 3, 4, 5], 2))



def reverse_skip(lst):
    return lst[-2::-2]


print(reverse_skip([1, 2, 3, 4, 5, 6]))





[1, 2, 3]
[4, 5]
[5, 3, 1]


**4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

**• Requirements:**
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

**• Requirements:**
– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,2], the output should be 6.

**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

**• Requirements:**
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

**• Requirements:**
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.





6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.
• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [8]:
# 1
def flatten(lst):
    return [item for sublist in lst for item in sublist]

print(flatten([[1, 2], [3, 4], [5]]))


# 2
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(nested_list, [1, 2]))


# 3
def sum_nested(lst):
    if isinstance(lst, int):
        return lst
    return sum(sum_nested(item) for item in lst)

print(sum_nested([[1, 2], [3, [4, 5]], 6]))


# 4
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))


# 5
def find_max(lst):
    if isinstance(lst, int):
        return lst
    return max(find_max(item) for item in lst)

print(find_max([[1, 2], [3, [4, 5]], 6]))


# 6
def count_occurrences(lst, elem):
    if isinstance(lst, int):
        return 1 if lst == elem else 0
    return sum(count_occurrences(item, elem) for item in lst)

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))


# 7
def deep_flatten(lst):
    if isinstance(lst, int):
        return [lst]
    return [item for sublist in lst for item in deep_flatten(sublist)]

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))


# 8
def average_nested(lst):
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)

print(average_nested([[1, 2], [3, 4], [5, 6]]))


[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


**10 To - Do - NumPy**

10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

Complete the following Tasks:

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [9]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-One Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_array = np.full((3, 3), 7)  # Example: 3x3 array filled with 7
print("\nArray Filled with 7:\n", fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])  # Reference array
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Reference Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty Array:
 [[6.53154946e-310 0.00000000e+000]
 [6.53156590e-310 6.53156590e-310]]

All-One Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Reference Array:
 [[0 0 0]
 [0 0 0]]

Ones Like Reference Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [10]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array Mean Value:\n", mean_value)

# 5. Create a 10x10 array with random values and find min & max
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 Random Matrix Min and Max:\n", min_value, max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4) set to 1
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill alternating positions with 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array Mean Value:
 0.5318797846156893

10x10 Random Matrix Min and Max:
 0.003697018945663877 0.9966333865098876

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.

{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [11]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array with any integer (let's choose 3)
mult_x = x * 3
print("\nMultiplication of x by 3:\n", mult_x)

# 4. Find the square of each element of the array
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Find the dot product:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("\nDot Product of v and w:", dot_vw)
print("\nDot Product of x and v:\n", dot_xv)
print("\nDot Product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows and v and w along columns
concat_xy = np.concatenate((x, y), axis=0)  # Row-wise
concat_vw = np.vstack((v, w))  # Column-wise

print("\nConcatenation of x and y along rows:\n", concat_xy)
print("\nConcatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError in concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot Product of v and w: 219

Dot Product of x and v:
 [29 77]

Dot Product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [12]:
# 1
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A_inv
identity_matrix = np.dot(A, A_inv)

print("A × A⁻¹:\n", identity_matrix)

# Check if it is an identity matrix
print("\nIs A × A⁻¹ equal to the identity matrix?:\n", np.allclose(identity_matrix, np.eye(2)))


# 2
# Given matrix B
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

# Check if AB and BA are equal
print("\nIs AB equal to BA?:", np.array_equal(AB, BA))



# 3

# Compute (AB)^T
AB_transpose = np.transpose(AB)

# Compute B^T and A^T
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)

# Compute B^T * A^T
BT_AT = np.dot(B_transpose, A_transpose)

print("(AB)^T:\n", AB_transpose)
print("\nB^T A^T:\n", BT_AT)

# Check if (AB)^T equals B^T A^T
print("\nIs (AB)^T equal to B^T A^T?:", np.array_equal(AB_transpose, BT_AT))


# 4

# Define matrix A and B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Compute inverse of A
A_inv_eq = np.linalg.inv(A_eq)

# Solve for X
X = np.dot(A_inv_eq, B_eq)

print("Solution (x, y, z):", X)


A × A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A × A⁻¹ equal to the identity matrix?:
 True
AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?: False
(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T?: True
Solution (x, y, z): [ 2.  1. -2.]
